### PR TITLE
Talk card

### PR DESCRIPTION
**Pull request by DrShpongle**
It's the way we did it with Vojta. What do you think?

Image 2020-11-21 at 11 04 33 AM

https://og-image-egghead-git-en-talk-card.eggheadio1.vercel.app/talk/egghead-egghead-talks-sleeping-better-at-night

### CODE REVIEW

**Comment by joelhooks** [comment]
@vojtaholik should the talk card highlight the speaker?

**Comment by DrShpongle** [comment]
Imo Talk should look like Podcast card, talk is rather podcast than lesson to me

**Comment by joelhooks** [comment]
if like it to look uinique feature the presenters face

this looks like a playlist generic to me and i prefer the “lesson with face” version that is love now, but don’t think it is good either

**Comment by joelhooks** [comment]
I don't like this much. I like the social share cards that we use to promote the talks. Can these look like those?

**Comment by vojtaholik** [comment]
@joelhooks updated
egghead-egghead-talks-learning-tips-every-developer-should-know

Closing this as I ended up working in main branch instead.

**Pull request closed without merging**
